config/routes.rb
require 'resque/server'

Refinery::Application.routes.draw do
  scope(:module => 'refinery') do
    resources :raw_videos, :path => 'videos', :only => [:show]
  
    scope(:module => 'admin', :path => 'refinery', :as => 'refinery_admin') do
      resources :raw_videos, :path => 'videos', :except => :show do
        collection do
          post :upload
          post :update_positions
        end
      end
    end
  end

  mount Resque::Server, :at => "/resque"
end

app/models/refinery/encoded_video.rb
module Refinery
  class EncodedVideo < ActiveRecord::Base

    belongs_to :raw_video
    
    video_accessor :file
    attr_accessible :file
    delegate :name, :uid, :mime_type, :v_height, :v_width, :ext, :frame_rate, :to => :file
    delegate :duration, :bitrate, :size, :stream, :codec, :colorspace, :resolution, :to => :file
    delegate :audio_stream, :audio_codec, :audio_sample_rate, :audio_channels, :to => :file
    delegate :url, :remote_url, :to => :file

    validates :file, :presence => true
    validates :raw_video, :presence => true
    validates :format, :presence => true
  
    acts_as_indexed :fields => [:name]
    
    scope :by_format, proc { |frmt| where(:format => frmt) }
    
  end
end

app/models/refinery/raw_video.rb
module Refinery
  class RawVideo < ActiveRecord::Base

    has_many :encoded_videos
    
    belongs_to :poster_image, :class_name => 'Refinery::Image'
    attr_accessible :poster_image_id
    
    video_accessor :file
    attr_accessible :file
    
    delegate :name, :uid, :mime_type, :v_height, :v_width, :ext, :frame_rate, :to => :file
    delegate :duration, :bitrate, :size, :stream, :codec, :colorspace, :resolution, :to => :file
    delegate :audio_stream, :audio_codec, :audio_sample_rate, :audio_channels, :to => :file
    delegate :url, :remote_url, :to => :file

    validates :file, :presence => true

    acts_as_indexed :fields => [:name]
    
    class << self
      def create_video(params)
        if Videos::Options.use_nginx_upload_module
          create_video_from_nginx_upload(params)
        else
          create(params[:raw_video])
        end
      end
              
      def html5_sort(encoded_videos)
        encoded_videos.sort do |vid_1, vid_2|
          self.format_weight(vid_1.format) <=> self.format_weight(vid_2.format)
        end
      end
      
      protected
      
        def create_video_from_nginx_upload(params)
          video_path = File.join(File.dirname(params[:nginx_upload][:path]), params[:nginx_upload][:file_name])
          FileUtils.mv(params[:nginx_upload][:path], video_path)
          begin
            params[:raw_video][:file] = Pathname.new(video_path)
            new_video = create(params[:raw_video])
          ensure
            FileUtils.rm(video_path)
          end
        end
    end
    
    def encode(format, options = {})
      options.symbolize_keys!
      
      EncodedVideo.create! do |encoded_video|
        encoded_video.raw_video = self
        encoded_video.file = self.file.html5(format, options).apply
        encoded_video.format = format.to_s
      end
    end
    
    def async_encode(*formats)
      formats.each { |format| Resque.enqueue(Refinery::EncodeVideo, self.id, format) }
    end

    def title
      CGI::unescape(name.to_s).gsub(/\.\w+$/, '').titleize
    end
  
    def encoded?
      !self.encoded_videos.by_format('mp4').empty? && 
      !self.encoded_videos.by_format('ogv').empty? &&
      !self.encoded_videos.by_format('webm').empty?
    end
    
    def poster_image_url
      self.poster_image.present? ? self.poster_image.image.url : nil
    end
    
    private
    
      @@format_weights = {
        'mp4' => 1,
        'webm' => 2,
        'ogv' => 3
      }
      
      class << self
        def format_weight(format)
          weight = @@format_weights[format]
          weight ? weight : 0
        end
      end
    
  end
end

app/controllers/refinery/admin/raw_videos_controller.rb
module Refinery
  module Admin
    class RawVideosController < Refinery::AdminController
      
      respond_to :html

      crudify :'refinery/raw_video',
              :title_attribute => 'title',
              :searchable => true,
              :sortable => false
            
      def create
        @raw_video = RawVideo.create_video(params)
        
        if @raw_video
          @raw_video.async_encode(:mp4, :ogv, :webm)
          flash[:notice] = t('encoding', :scope => 'refinery.admin.raw_videos', :title => @raw_video.title)
        end
        
        respond_with [:refinery_admin, @raw_video], :location => main_app.refinery_admin_raw_videos_path
      end
      alias_method :upload, :create
      
    end
  end
end

app/controllers/refinery/admin/videos_controller.rb
module Refinery
  module Admin
    class VideosController < Refinery::AdminController
      
      respond_to :html

      crudify :'refinery/raw_video',
              :title_attribute => 'title',
              :searchable => true,
              :sortable => false
            
      def create
        if nginx_upload?
          @raw_video = RawVideo.create_from_nginx_upload(nginx_params[:raw_video])
        else
          @raw_video = RawVideo.create(params[:raw_video])
        end
        
        if @raw_video
          @raw_video.async_encode(:mp4, :ogv, :webm)
          flash[:notice] = t('encoding', :scope => 'refinery.admin.videos', :title => @raw_video.title)
        end
        
        respond_with [:refinery_admin, @raw_video], :location => main_app.refinery_admin_videos_path
      end
      alias_method :upload, :create
      
      protected

        def nginx_upload?
          # TODO: Make this configurable
          params[:nginx_upload]
        end
        
        def nginx_params
          # TODO: Make this configurable
          params[:nginx_upload]
        end
    end
  end
end

app/controllers/refinery/raw_videos_controller.rb
module Refinery
  class RawVideosController < ::ApplicationController
    
    respond_to :html

    def show
      @raw_video = RawVideo.find(params[:id])

      respond_with(@raw_video)
    end

  end
end

app/controllers/refinery/videos_controller.rb
module Refinery
  class VideosController < ::ApplicationController
    
    respond_to :html

    def show
      @raw_video = RawVideo.find(params[:id])

      respond_with(@raw_video)
    end

  end
end

app/helpers/refinery/videos_helper.rb
module Refinery
  module VideosHelper
    def render_video_player(raw_video)
      video_urls = RawVideo.html5_sort(raw_video.encoded_videos).collect do |encoded_video|
        encoded_video.remote_url
      end
      
      video_tag(video_urls, 
        :class => "sublime", 
        :size => "768x428", 
        :poster => raw_video.poster_image_url,
        :preload => "none"
      )
    end
  end
end

app/views/refinery/admin/raw_videos/_actions.html.erb
<ul>
  <% if ::Refinery::Admin::RawVideosController.searchable? %>
    <li>
      <%= render :partial => "/refinery/admin/search",
                  :locals => {
                    :url => main_app.refinery_admin_raw_videos_path
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), main_app.new_refinery_admin_raw_video_path, :class => "add_icon" %>
  </li>
  <li>
    <%= link_to t('.resque'), "/resque", :class => "go_icon" %>
  </li>
</ul>

app/views/refinery/admin/raw_videos/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'refinery.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @raw_videos.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'videos' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'refinery.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/refinery/admin/raw_videos/_upload_progress_bar.html.erb
<% content_for :stylesheets do %>
<%= stylesheet_link_tag "refinery/admin/upload_progress" %>
<% end %>
<% content_for :javascripts do %>
<%= javascript_include_tag "refinery/admin/videos" %>
<script type="text/javascript">
  $(function() {
    $('form').uploadProgress({
  		jqueryPath: '<%= asset_path "jquery.js" %>',
  		uploadProgressPath: '<%= asset_path "jquery.uploadProgress.js" %>',
  		uploading: function(upload) {
  		  $('#percents').html(upload.percents+'%');
  		},
  		progressBar: "#progressbar",
  		progressUrl: '<%= Refinery::Videos::Options.upload_progress_uri %>',
  		interval: 2000,
  		dataType: 'json'
    });
  });
</script>
<% end %>
<div id="progress" class="bar">
  <div id="progressbar">&nbsp;</div>
  <div id="percents"></div>
</div>

app/views/refinery/admin/raw_videos/_video.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(video) -%>">
  <span class='title'>
    <%= video.title %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <% if video.encoded? %>
      <%= link_to refinery_icon_tag("application_go.png"), main_app.raw_video_path(video),
          :title => t('.view_live_html'),
          :target => "_blank" %>
      <%= link_to refinery_icon_tag("application_edit.png"), main_app.edit_refinery_admin_raw_video_path(video), :title => t('.edit') %>
      <%= link_to refinery_icon_tag("delete.png"), main_app.refinery_admin_raw_video_path(video),
          :class => "cancel confirm-delete",
          :title => t('.delete'),
          :confirm => t('message', :scope => 'refinery.admin.delete', :title => video.name),
          :method => :delete %>
    <% else %>
      Video is encoding
    <% end %>
  </span>
</li>

app/views/refinery/admin/raw_videos/_videos.html.erb
<%= will_paginate @raw_videos %>
<ul class="<%= ['pagination_frame', pagination_css_class].compact.join(' ') %>">
  <%= render :partial => "video", :collection => @raw_videos %>
</ul>

app/views/refinery/admin/raw_videos/edit.html.erb
<%= form_for [main_app, :refinery_admin, @raw_video], :html => { :method => :put } do |f| -%>
  <%= render :partial => "/refinery/admin/error_messages", :locals => {
          :object => @raw_video,
          :include_object_name => true
        } %>
    
  <div class='field'>
    <%= f.label :poster_image %>
    <%= render :partial => "/refinery/admin/image_picker", :locals => {:f => f, :field => :poster_image_id, :image => @raw_video.poster_image } %>
  </div>
  
  <%= render :partial => "/refinery/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'refinery.videos.video'),
                :delete_confirmation => t('message', :scope => 'refinery.admin.delete', :title => 'hi')
              } %>
<% end -%>

app/views/refinery/admin/raw_videos/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>

app/views/refinery/admin/raw_videos/new.html.erb
<%= form_for [main_app, :refinery_admin, @raw_video], :url => main_app.upload_refinery_admin_raw_videos_path, :html => { :method => :post, :multipart => true } do |f| -%>
  <%= render :partial => "/refinery/admin/error_messages", :locals => {
          :object => @raw_video,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.file_field :file %>
  </div>
  
  <div class='field'>
    <%= f.label :poster_image %>
    <%= render :partial => "/refinery/admin/image_picker", :locals => {:f => f, :field => :poster_image_id, :image => @raw_video.poster_image } %>
  </div>
  
  <%= render :partial => "/refinery/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'refinery.videos.video'),
                :delete_confirmation => t('message', :scope => 'refinery.admin.delete', :title => 'hi')
              } %>
<% end -%>

<%= render :partial => 'upload_progress_bar' if Refinery::Videos::Options.upload_progress_uri %>

app/views/refinery/admin/videos/_actions.html.erb
<ul>
  <% if ::Refinery::Admin::VideosController.searchable? %>
    <li>
      <%= render :partial => "/refinery/admin/search",
                  :locals => {
                    :url => main_app.refinery_admin_videos_path
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), main_app.new_refinery_admin_video_path, :class => "add_icon" %>
  </li>
  <li>
    <%= link_to t('.resque'), "/resque", :class => "go_icon" %>
  </li>
</ul>

app/views/refinery/admin/videos/_form.html.erb
<%= form_for [main_app, :admin, @raw_video], :url => main_app.upload_refinery_admin_videos_path, :html => { :method => :post, :multipart => true } do |f| -%>
  <%= render :partial => "/refinery/admin/error_messages", :locals => {
          :object => @raw_video,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.file_field :file, :multiple => (true unless @raw_video.persisted?) %>
  </div>
  
  <%= render :partial => "/refinery/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'refinery.videos.video'),
                :delete_confirmation => t('message', :scope => 'refinery.admin.delete', :title => 'hi')
              } %>
<% end -%>

app/views/refinery/admin/videos/_video.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(video) -%>">
  <span class='title'>
    <%= video.title %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <% if video.encoded? %>
      <%= link_to refinery_icon_tag("application_go.png"), main_app.video_path(video),
          :title => t('.view_live_html'),
          :target => "_blank" %>
      <% # link_to refinery_icon_tag("application_edit.png"), edit_admin_video_path(video), :title => t('.edit') %>
      <%= link_to refinery_icon_tag("delete.png"), main_app.refinery_admin_video_path(video),
          :class => "cancel confirm-delete",
          :title => t('.delete'),
          :confirm => t('message', :scope => 'shared.admin.delete', :title => video.name),
          :method => :delete %>
    <% else %>
      Video is encoding
    <% end %>
  </span>
</li>

app/views/refinery/raw_videos/_video.html.erb
<div id="<%= video.id %>" class="sublime-box">
  <%= render_video_player(video) %>
</div>

app/views/refinery/raw_videos/show.html.erb
<%= content_for :javascripts_head do %>
<%= javascript_include_tag 'http://cdn.sublimevideo.net/js/4on6wa5x.js' %>
<% end %>

<div class="videos_content">
	<div class="layout_1">
		<div class="col1">
		  <%= render :partial => 'video', :object => @raw_video %>
		</div>
	</div>
</div>